config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from game.users.views import user_logout


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('game.users.urls', namespace='users')),
    # url(r'^accounts/', include('allauth.urls')),
    url(r'^logout/$', user_logout, name='account_logout'),
    # Your stuff: custom urls includes go here
    # url(r'start/', include('game.player.urls')),
    # url(r'^board/', include('game.board.urls', namespace='board')),

    url(r'^done/$', TemplateView.as_view(template_name='pages/done.html')),

    url(r'^solo/', include('game.control.urls', namespace='control')),
    url(r'^dynamic_mode/', include('game.interactive_shocks.urls', namespace='dynamic_mode')),
    url(r'^static_mode/', include('game.interactive_static.urls', namespace='static_mode')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

game/control/urls.py
from django.conf.urls import url


from .views import assign, submit_answer, play
from .views import instruction, exit_survey


urlpatterns = [
    url(r'^play/$', play, name='play'),
    url(r'^submit/$', submit_answer, name='submit'),
    url(r'^instruction/$', instruction, name='instruction'),
    url(r'^exit/$', exit_survey, name='exit'),
    url(r'^$', assign),
]

game/interactive/urls.py
from django.conf.urls import url


from .views import assign, lobby, exit_survey, done, instruction

urlpatterns = [
    url(r'^$', assign),
    url(r'^lobby/$', lobby, name='lobby'),
    # url(r'^play/$', play, name='play'),
    # url(r'^submit/$', submit_answer, name='submit'),
    # url(r'^view_answers/$', view_answers, name='view_answers'),
    url(r'^exit/$', exit_survey, name='exit'),
    url(r'^done/$', done, name='done'),
    url(r'^instruction/$', instruction, name='instruction'),
]

game/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(r'^start/$', views.start, name='start-game'),
    # url(r'^done/$', views.done, name='done'),
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

game/control/forms.py
from django import forms
from .models import Survey


class RoundForm(forms.Form):
    guess = forms.DecimalField(required=True, max_digits=3, decimal_places=2)


class CheckForm(forms.Form):
    Q1_choices = (('1', 'Estimate the correlation of two variables'),
                  ('2', 'Count the points in the picture'),
                  )
    q1 = forms.ChoiceField(label='Your goal in the game is to', widget=forms.RadioSelect(attrs={'class': 'form-group'}),
                           choices=Q1_choices)

    q2 = forms.DecimalField(label='The maximum correlation possible is', widget=forms.TextInput)
    #q3 = forms.DecimalField(label='and', widget=forms.TextInput)

    q4 = forms.ChoiceField(label='In this game, all correlations will be', widget=forms.RadioSelect,
                           choices=(('1', 'Negative or positive'),
                                    ('2', 'Only positive'),
                                    ))

    q5 = forms.ChoiceField(label='Have you participated in this study before?', widget=forms.RadioSelect,
                           choices=(('1', 'No'),
                                    ('2', 'Yes'),
                                    ))

    def clean(self):
        cleaned_data = super(CheckForm, self).clean()
        q1 = cleaned_data.get('q1')
        q2 = float(cleaned_data.get('q2'))
        #q3 = float(cleaned_data.get('q3'))
        q4 = cleaned_data.get('q4')
        q5 = cleaned_data.get('q5')

        #if q1 == '1' and q2 == -1 and q3 == 1 and q4 == '2' and q5 == '1':
        if q1 == '1' and q2 == 1 and q4 == '2' and q5 == '1':
            return cleaned_data
        raise forms.ValidationError('Some answers are wrong .. please go back and read the instructions carefully')


class ExitSurvey(forms.ModelForm):
    class Meta:
        model = Survey
        fields = ['gender', 'age', 'feedback', 'pay', 'bugs', 'education']

    def __init__(self, *args, **kwargs):
        super(ExitSurvey, self).__init__(*args, **kwargs)
        for f in ['gender', 'age', 'feedback', 'pay', 'bugs', 'education']:
            self.fields[f].required = False

game/control/views.py
from math import fabs
from random import choice
from datetime import timedelta

from django.contrib.auth import authenticate, login
from django.core.cache import cache
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.db import transaction

from game.contrib.random_user import random_user

from game.round.models import Round, Plot

from .forms import RoundForm, CheckForm, ExitSurvey
from .models import Control, Setting


def avatar(exclude=set()):
    avatars = {'bee.png', 'bird.png', 'cat.png', 'cow.png', 'elephant.png', 'lion.png', 'pig.png', 'cute_cat.png',
               'cute_panda.png', 'cute_giraffe.png', 'cute_owl.png', 'cute_cat_color.png', 'smart_dog.png',
               'smart_fox.png', 'smart_monkey.png', 'smart_deer.png'
               }
    return choice(list(avatars.symmetric_difference(exclude)))


def assign(request):
    if request.method == 'POST':
        return redirect('control:instruction')
    return render(request, 'pages/home2.html')


SECONDS = 30
DELAY = 7


# Create your views here.
@login_required(login_url='control:instruction')
def play(request):

    u = request.user
    if u.game_type != 'control':
        return redirect('/')

    game = Control.objects.get(user=u)

    if not game.check_done:
        if game.check >= 4:
            return redirect('control:exit')
        return redirect('control:instruction')

    played_rounds = Round.objects.filter(user=u)
    plot_pks = {i.plot.pk for i in played_rounds}

    remaining = int(game.max_rounds or 10) - len(plot_pks)

    if remaining == 0:
        game.end_time = timezone.now()
        game.save()
        return redirect('control:exit')

    round_data = cache.get('control-{}'.format(game.id))
    if round_data is None:
        # new user
        round_data = {'new_round': True}

    if round_data.get('new_round', False):
        if len(plot_pks) == 0:
            # first round no batch has been assigned yet
            if u.level == 'e':
                track = 1
            elif u.level == 'm':
                track = 2
            elif u.level == 'h':
                track = 3
            else:
                track = 1
                print('Error no LEVEL was found on the user object')
            plots = Plot.objects.filter(non_stationary_seq=track).order_by('seq')
            plot = plots[0]
            data = {'track': track, 'remaining': game.batch_size-1}
        else:
            data = cache.get('control_user_{}'.format(u.id))
            plots = Plot.objects.filter(non_stationary_seq=data.get('track')).order_by('seq')
            plot_seq = game.batch_size - data['remaining']
            plot = plots[plot_seq]
            data['remaining'] -= 1
        cache.set('control_user_{}'.format(u.id), data)
        with transaction.atomic():
            r, created = Round.objects.get_or_create(user=u, plot=plot, round_order=len(plot_pks))
        if created:
            extra = {'round_id': r.id}
        else:
            extra = None
            print('Tried to create a round with an old plot or round_order {}'.format(r))
    else:
        extra = None
        plot = Plot.objects.get(id=round_data.get('plot_id'))

    d = cache.get('control-{}'.format(game.id))
    payload = {
        'score': 0.0,
    }

    if extra:
        # new round was found
        payload = {
            'new_round': False,
            'plot_id': plot.id,
            'remaining': remaining - 1,
            'currentRound': len(plot_pks) + 1,
            'score': request.user.get_score,
        }
        payload.update(extra)

    if d:
        # there was new data  before
        if payload.get('currentRound', False):
            if payload.get('currentRound') > d.get('currentRound'):
                d = payload
            else:
                print('Cache has recent data than payload')
                return redirect('control:play')
        else:
            print('Found data in the cache and Payload is None')
            r = Round.objects.get(id=d.get('round_id'))
            if (r.start_time + timedelta(seconds=SECONDS + DELAY)) < timezone.now():
                cache.set('control-{}'.format(game.id), None)
                return redirect('control:play')
    else:
        d = payload

    cache.set('control-{}'.format(game.id), d)
    form = RoundForm()
    d['form'] = form
    d['round'] = plot
    return render(request, 'control/play.html', d)


# TODO: score, plots remaining off by one
@login_required(login_url='/')
def submit_answer(request):
    if request.method == 'POST':
        form = RoundForm(request.POST)
        if form.is_valid():
            guess = form.cleaned_data['guess']
            game = Control.objects.get(user=request.user)
            try:
                round_data = cache.get('control-{}'.format(game.id))
            except ValueError:
                round_data = {'plot_id': 1}
                print("Couldn't load from cache??")
            score = request.user.get_score
            plot = Plot.objects.get(id=round_data.get('plot_id'))
            r = Round.objects.get(user=request.user, plot=plot, round_order=round_data.get('currentRound')-1)

            if (r.start_time + timedelta(seconds=SECONDS + DELAY)) < timezone.now():
                guess = -1

            if r.guess is None:
                r.guess = guess
                r.score = score
                r.end_time = timezone.now()
                r.save()
            else:
                print("Either r.guess was found or the user didn't submit the answer within the allowed time")
                return redirect('control:play')
            round_data['round'] = plot
            round_data['guess'] = r.guess
            round_data['score'], round_data['bonus'] = request.user.get_score_and_gain
            if r.guess >= 0:
                round_data['difference'] = fabs(r.guess - plot.answer)
            round_data['new_round'] = True
            cache.set('control-{}'.format(game.id), round_data)
            return render(request, 'control/answer.html', round_data)

    return redirect('control:play')


def instruction(request):
    if request.user.is_anonymous:
        u, password = random_user('control', length=60)
        u.avatar = avatar()
        u.save()
        settings = Setting.objects.all()
        if settings.count() != 0:
            setting = settings.order_by('?')[0]
        else:
            setting = Setting.objects.create(max_rounds=10, batch_size=5)
        types = setting.types.split(',')
        try:
            d = {
                '0': 'e',
                '1': 'm',
                '2': 'h',
            }
            t = types.pop(0)
            u.level = d[t]
            u.save()
            setting.types = ','.join(types)
            setting.save()
        except (AttributeError, KeyError):
            print('Control types array is empty')
            return render(request, 'out_of_games.html')

        Control.objects.create(user=u, max_rounds=setting.max_rounds, batch_size=setting.batch_size)
        u = authenticate(username=u.username, password=password)
        login(request, u)

    u = request.user
    game = Control.objects.get(user=u)
    game.instruction = True
    game.save()
    
    form = CheckForm(request.POST or None)
    check_count = game.check
    if check_count >= 4:
        return redirect('control:exit')

    if request.method == 'POST':
        if form.is_valid():
            game = Control.objects.get(user=u, instruction=True, check=check_count)
            game.check_done = True
            game.save()
            return redirect('control:play')
        else:
            try:
                game = Control.objects.get(user=u, instruction=True)
                game.check += 1
                game.save()
            except Control.DoesNotExist:
                return redirect('control:instruction')
    return render(request, 'control/instructions.html', {'form': form})


@login_required(login_url='/')
def exit_survey(request):
    game = Control.objects.get(user=request.user)
    form = ExitSurvey(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user.username
            instance.game = game.id
            instance.save()
            return render(request, 'control/done.html')

    return render(request, 'control/survey.html', {'form': form, 'score':
        round(float(request.user.get_score or 0.0) / 10.0, 2)})

game/interactive/views.py
from django.contrib.auth import authenticate, login
from django.core.cache import cache
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from game.users.models import User
from game.contrib.random_user import random_user
from game.interactive.forms import ExitSurvey, CheckForm

from .models import Interactive, Settings


def assign(request):
    if request.method == 'POST':
        return redirect('interactive:instruction')
    return render(request, 'pages/home2.html')


# Create your views here.
@login_required(login_url='interactive:instruction')
def lobby(request):
    if cache.get('interactive_instruction_{}'.format(request.user.id)):
        return render(request, 'interactive/lobby.html')
    return redirect('interactive:instruction')


@login_required(login_url='/')
def exit_survey(request):
    """
    username = models.CharField(max_length=255, blank=True, null=True)
    game = models.OneToOneField(Interactive)
    age = models.PositiveSmallIntegerField(null=True)
    gender = models.CharField(max_length=10, choices=(('m', 'Male'),
                                                      ('f', 'Female'),
                                                      ), blank=True, null=True)
    feedback = models.TextField(null=True)
    :param request:
    :return:
    """
    form = ExitSurvey(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            u = User.objects.get(username=request.user.username)
            game = Interactive.objects.get(users=u)
            instance = form.save(commit=False)
            instance.username = u.username
            instance.game = game.id
            instance.save()
            return redirect('interactive:done')
        else:
            print('NOT Valid')
    return render(request, 'control/survey.html', {'form': form, 'score': request.user.get_score})


def done(request):
    return render(request, 'interactive/done.html')


def instruction(request):
    form = CheckForm(request.POST or None)
    if request.user.is_anonymous:
        u, password = random_user('i')
        u = authenticate(username=u.username, password=password)
        login(request, u)
        cache.set('interactive_instruction_{}'.format(u.id), False)
    else:
        u = request.user
        if u.game_type != 'i':
            return redirect('/')
    if request.method == 'POST':
        if form.is_valid():
            cache.set('interactive_instruction_{}'.format(u.id), True)
            return redirect('interactive:lobby')
    game_settings = Settings.objects.order_by('?')[0]

    # skip instructions for ease of development
    cache.set('interactive_instruction_{}'.format(u.id), True)
    return render(request, 'interactive/instructions.html', {'players_num': game_settings.max_users,
                                                             'rounds_num': game_settings.max_rounds,
                                                             'following_num': game_settings.max_following,
                                                             'form': form,
                                                             })

game/round/views.py
from django.shortcuts import render

# Create your views here.

game/templates/control/answer.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block breadcrumbs %}
<div>
   <ul class="nav nav-wizard">
       <li>Current Round: {{currentRound}}/{{ remaining|add:currentRound}}</li>
       <li><a>Your Guess</a></li>
       <li class='active'><a>Round Outcome</a></li>
   </ul>
</div>
{% endblock %}

{% block container %}
<div class="row">
<div class="col-md-1">
  {% include 'components/timer.html' %}
</div>
<div class="col-md-6">
  <img src="/static/plots/{{ round.plot }}" class="img-responsive faded" />
  <div class="form">
      <div id="answerSlider">
          <div class="ui-slider-handle"></div>
      </div>
    <div class="row">
      <div class="col-md-5"><b>Your guess:</b></div>
      {% if guess >= 0 %}
        <div class="col-md-2">{{guess}}</div>
      {% else %}
        <div class="col-md-2">N/A</div>
      {% endif %}
    </div>
    <div class="row">
      <div class="col-md-5"><b>Actual correlation:</b></div>
        <div class="col-md-2"><span id="roundAnswer">{{ round.answer }}</span></div>
    </div>
    <div class="row">
      <div class="col-md-5"><b>Score increment:</b></div>
      <div class="col-md-2"><span id="roundBonus">+{{ bonus }}</span></div>
    </div>
    <form action="{% url 'control:play' %}">
      <input type="submit" value="Next" id="submit" class="btn btn-success nextButton">
    </form>
  </div>
</div>

</div>
{% endblock %}

{% block extra_javascript %}
  <script src="{% static 'js/game.js' %}"></script>
    <script>
         $("#answerSlider").html("");
         var data = {guess: +{{guess}},
                     correct_answer: {{ round.answer }}
         };
      if(data.guess != -1) {
        $("#yourGuess").html({{ guess }});
        $("#answerSlider").slider({
          range: true,
          min: 0,
          max: 1,
          step: 0.01,
          values: [data.correct_answer, data.guess].sort(),
          disabled: true
        });
        if(data.guess > data.correct_answer) {
          $($("#answerSlider > .ui-slider-handle")[0]).addClass("true-answer");
        }
        else {
          $($("#answerSlider > .ui-slider-handle")[1]).addClass("true-answer");
        }
      }
      else {
        console.log("reset slider");
        $("#answerSlider").slider({
          range: true,
          min: 0,
          max: 1,
          step: 0.01,
          value: data.correct_answer,
          disabled: true
        });
        $($("#answerSlider > .ui-slider-handle")[0]).addClass("true-answer");
      }
    </script>
{% endblock %}

game/templates/control/check.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block container %}
<div id="instructionsCheck">
<h2>Comprehension Check</h2>
  <form class="form" action="." method="post">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <ul>
        <li><b>{{ error }}</b></li>
      </ul>
    {% endfor %}
    <div class="form-group">
      {{ form.q1.label }}
      {% for option in form.q1 %}
      <div> 
        {{ option }}
      </div>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.q2.label }} {{ form.q2 }} {{ form.q3.label }} {{ form.q3 }}
    </div>
    <div class="form-group">
      {{ form.q4.label }}
      {% for option in form.q4 %}
      <div> 
        {{ option }}
      </div>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.q5.label }}
      {% for option in form.q5 %}
      <div> 
        {{ option }}
      </div>
      {% endfor %}
    </div>

  <button type="submit" value="Submit" class="btn btn-info nextButton">Submit</button>
  </form>
    <a class="btn btn-primary" href="{% url 'control:instruction' %}">Previous</a>
</div>
{% endblock %}

game/templates/control/done.html
{% extends 'base.html' %}

{% block container %}
    <h2>Thanks for participating</h2>
    <p>Please don't forget to  submit the following code to receive your bonus</p>
    <p><strong>{{user.username}}</strong></p>
{% endblock %}

{% block extra_javascript %}
    <script>
    (function(){
        document.querySelector('.logout').style.display = 'none';
    })();
    </script>
{% endblock %}

game/templates/control/instructions.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block container %}
<div class="container" xmlns="http://www.w3.org/1999/html">
  <div class="overview">

  <div class="overview-1" id="overview-1">
    <h2>Game Instructions</h2>
    <p>
    <br>After completing the instructions and comprehension check, you will begin the game. The game consists of <b>20 rounds</b>. At each round you will see a scatter plot and be asked to <b>estimate the correlation of the X and Y variables</b>. <br> <a href="https://en.wikipedia.org/wiki/Pearson_product-moment_correlation_coefficient" target="_blank">Correlation</a> measures how strongly two variables are related to each other. For example, the graph below depicts the correlation between weight and height. As weight increases, height tends to increase as well.
    <img src="/static/images/height-age.png" class="img-responsive" />
    </p>
    <div class="row">
        <a class="btn btn-primary nextButton" href="#overview-2">Next</a>
    </div>
  </div>

  <div class="overview-2" id="overview-2" hidden>
      <h2>Game Instructions</h2>
    <p>
    Each round will consist of 2 stages: "Your Guess" and "Round Outcome".
    </p>
    <p>
    1. <strong>Your Guess</strong>: Guess the correlation of the plot shown. Use the slider below the plot to pick a value, and click "Submit" when you are ready. You can take maximum 30 seconds to submit.
    </p>
    <img src="/static/images/solo_stage1.png" class="img-responsive sample"/>
    <div class="row">
        <a class='btn btn-primary prevButton' href="#overview-1">Previous</a>
        <a class="btn btn-primary nextButton" href="#overview-3">Next</a>
    </div>
  </div>

  <div class="overview-3" id="overview-3" hidden>
      <h2>Game Instructions</h2>
    <p>
    2. <b>Round Outcome</b>: See your guess vs. the actual correlation value, as well as your score earned. Click “Next” to go to the next round.
    </p>
     <img src="/static/images/solo_stage2.png" class="img-responsive sample"/>
    <div class="row">
<a class='btn btn-primary prevButton' href="#overview-2">Previous</a>
        <a class="btn btn-primary nextButton" href="#overview-4">Next</a>
    </div>
  </div>


  <div class="overview-4" id="overview-4" hidden>
    <h2>Game Instructions</h2>
    <p>
    In this game, <strong>your correlation guess can range from 0 to 1</strong>, and the closer the points fit to a straight line, the closer the correlation will be to 1. No calculations are necessary, just make your best estimate.
    </p>
    <img src="/static/images/correlation-examples.png" class="img-responsive" />

    <div class="row">
      <a class='btn btn-primary prevButton' href="#overview-3">Previous</a>
        <a class="btn btn-primary nextButton" href="#overview-5">Next</a>
    </div>
  </div>

  <div class="overview-5" id="overview-5" hidden>
    <h2>Game Instructions</h2>
      <p>
          Note that <b>different scatter plots may have the same correlation value</b>. Plots can vary in number of points and shape, which can make them easier or harder to guess. For example, both plots in the first row below have a correlation of 0.89, and both plots in the second row a correlation of .55
      </p><p>
      You will see more than one type of plot along the 20 rounds.
  </p>
    <img src="/static/images/new_correlation.png" class="img-responsive" />

    <div class="row">
      <a class='btn btn-primary prevButton' href="#overview-4">Previous</a>
        <a class="btn btn-primary nextButton" href="#overview-6">Next</a>
    </div>
  </div>

  <div class="overview-6" id="overview-6" hidden>
    <h2>Comprehension Check</h2>
    <p>   </p>
    <form class="form" method="post">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <ul>
        <li><b>{{ error }}</b></li>
      </ul>
    {% endfor %}
    <div class="form-group">
      {{ form.q1.label }}
      {% for option in form.q1 %}
      <div> 
        {{ option }}
      </div>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.q2.label }} {{ form.q2 }} {{ form.q3.label }} {{ form.q3 }}
    </div>
    <div class="form-group">
      {{ form.q4.label }}
      {% for option in form.q4 %}
      <div> 
        {{ option }}
      </div>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.q5.label }}
      {% for option in form.q5 %}
      <div> 
        {{ option }}
      </div>
      {% endfor %}
    </div>
    <div class="row">
        <a class='btn btn-primary prevButton' href="#overview-5">Previous</a>
    <button type="submit" value="Submit" class="btn btn-danger nextButton">Submit</button>
    </div>
  </form>
  </div>

 </div>
</div>
{% endblock %}

{% block extra_javascript %}
  <script src="{% static 'js/game.js' %}"></script>
  <script src="{% static 'js/instructions.js' %}"></script>
{% endblock %}

game/templates/control/play.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block breadcrumbs %}
<div>
   <ul class="nav nav-wizard">
       <li>Current Round: {{currentRound}}/{{ remaining|add:currentRound}}</li>
       <li class='active'><a>Your Guess</a></li>
       <li><a>Round Outcome</a></li>
   </ul>
</div>
{% endblock %}

{% block container %}
<div class="row">
<div class="col-md-1">
    {% include 'components/timer.html' %}
  </div>
  <div class="col-md-6">
  <form action='{% url "control:submit" %}' method="post">
    {% csrf_token %}
    <div>
      <img src="/static/plots/{{ round.plot }}" class="img-responsive"/>
    </div>
    {% include 'components/slider.html' %}
    <div class="row">
      <input class='btn btn-success nextButton' type="submit" id="submit" value="Submit" disabled>
    </div>
  </form>
  </div>
</div>

{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'js/game.js' %}"></script>
{% endblock %}

game/templates/control/survey.html
{% extends 'base.html' %}

{% block container %}
<div class="survey">
<h2>Exit Survey</h2>
    <p>Please submit the following code to receive your bonus</p>
    <p><strong>{{user.username}}</strong></p>
    <p>Your final <b>bonus</b> is ${{score}} in addition of the <b>$2 base reward</b> for completing the HIT.</p>
    <p>Please answer the following short survey. You do not have to provide any information you feel uncomfortable with.</p>
<hr>
  <form class="form-inline" action="." method="post">
    {% csrf_token %}
        <div>
            {% if form.errors %}
                {{ form.errors }}
            {% endif %}
        </div>
            <div class="form-group">
                <label for="age">
                    Age
                </label>
                <input class="form-control" id="age" name="age">
            </div>
            <div class="form-group">
                <label for="gender">
                    Gender
                </label>
                <input class="form-control" type="text" id="gender" name="gender"/>
            </div><div><br></div>
        <div class="form-group">
            <label for="education">Highest educational qualification</label> <br>
            <input type="radio" id='education' name="education" value="highschool">High School<br>
            <input type="radio" id='education' name="education" value="bachelor">US Bachelor's degree<br>
            <input type="radio" id='education' name="education" value="master">Master's or higher<br>
            <input type="radio" id='education' name="education" value="other">Other<br>
        </div><hr>
  <div class="form-group">
      <label for="bugs">Have you noticed any bugs or problems in the game?</label><br>
      <textarea id='bugs' rows="1" cols="60" class="form-control" name="bugs"></textarea>
  </div>
  <div class="form-group">
      <label for="pay">Do you feel the pay was fair?</label><br>
      <textarea id='pay' rows='1' cols="60" class="form-control" name="pay"></textarea>
  </div>
      <div class="form-group">
          <label for="feedback">
              Please enter any feedback, including problems you encountered.
          </label>
        <textarea id='feedback' rows="1" cols="60" class="form-control" name="feedback"></textarea><br>
      </div>
  <div class="form-group">
      <button class="btn btn-primary nextButton" type="submit">Submit HIT</button>
  </div>
  </form>
</div>
{% endblock %}

{% block extra_javascript %}
    <script>
    (function(){
        document.querySelector('.logout').style.display = 'none';
    })();
    </script>
{% endblock %}